### ISSUE TITLE
Fails in Python 3.5.2 - module 'itertools' has no attribute 'imap'

### ISSUE THREAD

**Issue by alan1world** [miracle2k/python-glob2#14]
According to [this stackoverflow answer](http://stackoverflow.com/questions/30271712/i-cant-find-imap-in-itertools-in-python), imap was removed from itertools because map now supplies the same functionality.

_Full message:_

> > > all_header_files = glob2.glob('*_/_.htm')
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/lib/python3.5/site-packages/glob2/impl.py", line 54, in glob
> > >     return list(self.iglob(pathname, with_matches, include_hidden))
> > >   File "/usr/lib/python3.5/site-packages/glob2/impl.py", line 76, in iglob
> > >     return itertools.imap(lambda s: s[0], result)
> > > AttributeError: module 'itertools' has no attribute 'imap'

**Comment by arnaudlamy** [comment]
+1

**Comment by petebrowne** [comment]
I'm also running into this issue
