### ISSUE TITLE
pypi overwrote 0.4.1

### ISSUE THREAD

**Issue by nricklin** [miracle2k/python-glob2#16]
Looks like you guys somehow uploaded version 0.4.1 to pypi and overwrote the previous "version" of 0.4.1 with different code.

Might wanna upgrade the version before pushing to pypi, this broke stuff for us.

**Comment by miracle2k** [comment]
I fucked that up badly - sorry. I wanted to just add a wheel to the old release.

I removed the incorrect wheel from 0.4.1 on PyPI to restore the old behaviour, and published a new version, with a wheel, as 0.5.
