### ISSUE TITLE
New release possible?

### ISSUE THREAD

**Issue by mingwandroid** [miracle2k/python-glob2#23]
In particular this commit is needed by users of py.test to prevent the deprecation warning:

https://github.com/miracle2k/python-glob2/commit/be6981ec1a3ec089a934dbce3717d9ee6a01584e#diff-f8c62b113ad2e516e1ef8f0e9349800b

**Comment by mingwandroid** [comment]
Ping?

**Comment by duhaime** [comment]
@miracle2k Any chance you can do a little `python setup.py sdist upload` for the good people who love your work?

**Comment by miracle2k** [comment]
Done.
