### ISSUE TITLE
No option to override the excluding of hidden files?

### ISSUE THREAD

**Issue by mgoodfellow** [miracle2k/python-glob2#7]
Hi,

From what I can see of the code, there is no way to override whether it looks at hidden files. I think this feature could be added by overriding the [check](https://github.com/miracle2k/python-glob2/blob/master/glob2/impl.py#L162) but before I look at creating a PR I wanted to see if this was something you were interested in?

Thanks!

**Comment by miracle2k** [comment]
I believe the default behaviour of the Python glob module is this, and I wouldn't want to deviate from that.

Are you asking for the ability to overwrite the Globber class to modify this behaviour? Then yes, I think there is nothing wrong with having that ability. Maybe just pulling ``_is_hidden`` into the class could do the trick.

**Comment by mgoodfellow** [comment]
Thanks for the fast reply! Yes, this was along the lines I was thinking, as custom globber classes could then be created allowing for hidden files. I will look at making this change and opening a PR in the near future.
