### ISSUE TITLE
Merging with coala glob

### ISSUE THREAD

**Issue by sils1297** [miracle2k/python-glob2#8]
Hi,

we have created a glob library similar to yours for the coala project. Currently I'm looking into possibilities of splitting out general purpose parts into own libraries and merge with existent projects where possible.

Would you be open for such a merge? We have quite similar functionality as far as I can see from roughly reading over your readme.

Our code is at https://github.com/coala-analyzer/coala/blob/master/coalib/parsing/Globbing.py and our tests reside at https://github.com/coala-analyzer/coala/blob/master/coalib/tests/parsing/GlobbingTest.py . That said, our glob module is fully tested with continuous integration against windows, linux and mac with full test branch coverage which is one of the main benefits you'd get from the merge - mature stability. With the merge we can also offer maintenance help, setting up proper CI doing automated releases and that stuff if this is desired as we will continue to use the library.

**Comment by sils1297** [comment]
Oh I forgot we have specified our Glob syntax at http://coala.readthedocs.org/en/latest/Users/Glob_Patterns/

**Comment by sils1297** [comment]
Just thinking, we could also throw in our string processing library which allows working with regexes easier making this a more allround stuff-matching library. We have especially looked into searching strings for unescaped sequences.

https://github.com/coala-analyzer/coala/blob/master/coalib/parsing/StringProcessing.py

The test stuff applies here too, thats coala philosophy.

**Comment by miracle2k** [comment]
It's interesting, but apologies, my time is limited to approving pull requests on this lib regarding specific additions.

**Comment by sils1297** [comment]
@miracle2k well we'd do a PR and maybe help you maintaining because globs are relevant. If that's interesting to you, we'll think about that further and you might get a PR.

**Comment by miracle2k** [comment]
I am happy about PRs, though they should have a specific scope (e.g. "adding Travis CI"). My concern with a big, fat merge is that it will be hard for me review it. My goal is to maintain this libraries compatibility with the default glob.
